

# Travis-CI Build for kst2
# see travis-ci.org for details

language: erlang

      
install:
 - sudo apt-get remove cmake mingw32-binutils mingw32-runtime mingw32 libqt4-dev qt4-qmake mingw-w64 g++-mingw-w64 gcc-mingw-w64
 - sudo apt-get install m4 bison flex
 - sudo apt-get autoremove

script:
# - ./cmake/travis.sh qt4
 - ./cmake/travis.sh qt5

branches:
 only:
   - master
   
